### ISSUE TITLE
is robinhood crypto orders disabled?

### ISSUE THREAD

**Issue by dudeoverhere** [jmfernandes/robin_stocks#258]
All the other trading functions work but the order_crypto function doesn't work?

Did robinhood disable the feature?

using this code:
## version 03

import robin_stocks.robinhood as rs
from my_start import username, mypassword
import time

login = rs.login(username,mypassword)

time.sleep(3)

## this works
rs.order('SPY', 1, 'buy', 1)

time.sleep(3)

## this doesnt work
rs.order_crypto('ETH', 'buy', 1, "quantity", 1)

time.sleep(3)
rs.logout()

I get this error:
Traceback (most recent call last):
  File "00_v03.py", line 18, in <module>
    rs.order_crypto('ETH', 'buy', 1, "quantity", 1)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/robin_stocks/robinhood/helper.py", line 33, in login_wrapper
    return(func(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/robin_stocks/robinhood/orders.py", line 1442, in order_crypto
    url = order_crypto()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/robin_stocks/robinhood/helper.py", line 33, in login_wrapper
    return(func(*args, **kwargs))
TypeError: order_crypto() missing 3 required positional arguments: 'symbol', 'side', and 'quantityOrPrice'
>>>

**Comment by TKassis** [comment]
Remove the last '1' argument.
