### ISSUE TITLE
502 Server Error: Bad Gateway for url: https://nummus.robinhood.com/currency_pairs/

### ISSUE THREAD

**Issue by PAujla03** [jmfernandes/robin_stocks#267]
Hi, 

I keep getting the 502 Server Error when I try to run
r.crypto.get_crypto_historicals('BTC', '15second', 'hour', info='high_price')

Any suggestion would be appreciated.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/robin_stocks/robinhood/helper.py", line 33, in login_wrapper
    return(func(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/robin_stocks/robinhood/crypto.py", line 212, in get_crypto_historicals
    id = get_crypto_info(symbol[0], info='id')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/robin_stocks/robinhood/crypto.py", line 103, in get_crypto_info
    data = [x for x in data if x['asset_currency']['code'] == symbol]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/robin_stocks/robinhood/crypto.py", line 103, in <listcomp>
    data = [x for x in data if x['asset_currency']['code'] == symbol]
TypeError: 'NoneType' object is not subscriptable

**Comment by xinxic** [comment]
I got the same issue.

**Comment by PAujla03** [comment]
The only success I have had is with method r.load_account_profile()
All methods in crypto.py and some in orders.py have failed for me.

**Comment by PAujla03** [comment]
I guess this explains it...

https://finance.yahoo.com/news/robinhood-says-crypto-trading-having-030434053.html

Time to close this mystery.
