### ISSUE TITLE
issue with build_holdings method

### ISSUE THREAD

**Issue by kiranshivaling** [jmfernandes/robin_stocks#29]
Hi, 
I am getting the following error while trying to use "build_holdings()" methods 

Traceback (most recent call last):
  File "a.py", line 6, in <module>
    my_stocks = robin_stocks.build_holdings()
  File "/usr/local/lib/python3.5/dist-packages/robin_stocks/helper.py", line 20, in login_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/robin_stocks/account.py", line 490, in build_holdings
    holdings[symbol].update({'name': stocks.get_name_by_symbol(symbol)})
  File "/usr/local/lib/python3.5/dist-packages/robin_stocks/stocks.py", line 139, in get_name_by_symbol
    if not data['simple_name']:
TypeError: 'NoneType' object is not subscriptable

My code is simple:
import robin_stocks
robin_stocks.login('xxxxxx','xxx')
my_stocks = robin_stocks.build_holdings()
print (my_stocks)

**Comment by jmfernandes** [comment]
could you provide more information?

**Comment by jmfernandes** [comment]
Fixed in github code.
