### ISSUE TITLE
401 Client Error: Unauthorized for url: https://api.robinhood.com/quotes/historicals/?

### ISSUE THREAD

**Issue by wyattdt** [jmfernandes/robin_stocks#293]
C:\RobinHoodbottest folder>python Trader.py
stocks: ['fami', 'sndl', 'itp']
holdings: {'fami': 0, 'sndl': 0, 'itp': 0}
fami = $0.4871
401 Client Error: Unauthorized for url: https://api.robinhood.com/quotes/historicals/?symbols=FAMI&interval=5minute&span=day&bounds=regular
The error
[None]
Traceback (most recent call last):
  File "C:\RobinHoodbottest folder\Trader.py", line 119, in <module>
    trade = ts.trade_option(stock, price)
  File "C:\RobinHoodbottest folder\trade_strat.py", line 58, in trade_option
    df_historical_prices = self.get_historical_prices(stock, span='day')
  File "C:\RobinHoodbottest folder\trade_strat.py", line 32, in get_historical_prices
    for subitem in item['historicals']:
TypeError: 'NoneType' object is not subscriptable

**Comment by wyattdt** [comment]
any idea why i am getting this error 
401 Client Error: Unauthorized for url: https://api.robinhood.com/quotes/historicals/?symbols=FAMI&interval=5minute&span=day&bounds=regular

**Comment by kimardenmiller** [comment]
Started seeing 401s on everything this morning:

````401 Client Error: Unauthorized for url: https://api.robinhood.com/quotes/?symbols=AMD````

Login seems fine, but RH just rejecting requests all the sudden. 

Also noticing that logging in under the RS library is not creating a device on RH, which it used to do. But RH still lets me log out and back in with my last-created backup code, so I can't really see any issues with authentication. 

Anyone else seeing this behavior show up as of the evening of July 21, 2021?

**Comment by nickdela** [comment]
works as intended for me as of just now

**Comment by kimardenmiller** [comment]
SOLVED: Related to issue #296, the fact that we have to comment out `/robin_stocks/robinhood/authentication.py:130` means there is no warning when authentication fails. Temporarily uncommenting that line showed that my TOTP key was no longer working (for some unknown reason). Generating a new TOTP restored my ability to authenticate. 

REMAINING ISSUES:

1. Why does `/robin_stocks/robinhood/authentication.py:130` need to be commented out to prevent creating an infinite number of devices on Robinhood and eventually failing authentication?
2. Even with the line commented out, why does the TOTP eventually stop working?

**Comment by kimardenmiller** [comment]
My above fix of generating a new TOTP key worked from that date to this date (~6 weeks) authenticating roughly 10 times a week, then again stopped working. Generating a new key once again fixed it. Anyone have any ideas what's going on?

**Comment by monkeyden** [comment]
Just ran into this issue myself.  I tried commenting out that line in authentication.py and resetting TOTP, with no luck.  I also stepped into the get_stocks_historicals() and request_get() methods in the debugger, to inspect state.  Nothing seems out of place in the SESSION object and the _data_ that comes back doesn't contain any useful context for the 401.  I'm sort of dead in the water at the moment.

**Comment by kimardenmiller** [comment]
The approach in #312 is the one I took, which has solved the issue for months now. The approach in #300 might work, but did not make sense to me.

**Comment by monkeyden** [comment]
Not sure how it relates, unless the root cause is the shared request_get() call, in which case the solution (rh.get_events('GM')) doesn't seem to address.  I'm trying to retrieve OHLC history and getting that error.  They seem to be getting options events.

401 Client Error: Unauthorized for url: https://api.robinhood.com/quotes/historicals/?symbols=SNDL&interval=hour&span=week&bounds=regular

**Comment by kimardenmiller** [comment]
If you
> tried commenting out that line in authentication.py and resetting TOTP, with no luck

then it's not related. Did you comment out the correct `authentication.py`? There are two. You need the one at `/robin_stocks/robinhood`.

**Comment by monkeyden** [comment]
VSCode found exactly one occurrence, unless it's another line with different content.
![image](https://user-images.githubusercontent.com/2170790/148633060-4f1127ba-e40f-4109-b594-b51bc0a80c63.png)

**Comment by kimardenmiller** [comment]
Looks as if there have been several updates to the code. I'm on 2.0.4. The latest code looks completely different, absoleting this thread I think. Suggest we close.

**Comment by HMSS013** [comment]
hey all, i have run into this issue twice over the past few years... here is what i know...

i do not believe it is an issue with the code... Robinhood appears to block access if it receives an abnormal burst of requests.

if you view "Devices" under your account security you will see how they identify the browser as **Mobile Safari UI/WKWebView (iOS)** ... when a burst of requests triggers the block all activity from this browser type is denied for an unspecified amount of time.

when this happened to me in October of 2020 i believe it was six weeks and then the problem resolved itself... most recently it has been two months and counting.

i manage a number of accounts in parallel using identical software and the issue occurs randomly and never affects all accounts.

it would be interesting to test this theory by spoofing the user agent of a browser to match and seeing if it gets denied.

**Comment by Adelantado** [comment]
@kimardenmiller REMAINING ISSUES:

Why does /robin_stocks/robinhood/authentication.py:130 need to be commented out to prevent creating an infinite number of devices on Robinhood and eventually failing authentication?

My ISSUE:
Even after commenting line 130, I keep creating and logging a new device every time. I have listed thousands on my phone app but can't delete them because App freezes every time it trys to load them.  Via browser does not display them, only the last few recently created.  Any suggestions ??
