### ISSUE TITLE
Can't run on Mac M1

### ISSUE THREAD

**Issue by willswinson** [jmfernandes/robin_stocks#405]
Error below:

```
ImportError: dlopen(/.../site-packages/_cffi_backend.cpython-39-darwin.so, 0x0002): tried: '/.../site-packages/_cffi_backend.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/.../site-packages/_cffi_backend.cpython-39-darwin.so' (no such file), '/.../site-packages/_cffi_backend.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
thread '<unnamed>' panicked at 'Python API call failed', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.15.2/src/err/mod.rs:582:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/.../foobar.py", line 17, in <module>
    from indicators.bot_main import BotMain
  File "/.../foorbar.py", line 10, in <module>
    from data.data_controller import DataController
  File "/..../foobar.py", line 8, in <module>
    import robin_stocks.robinhood as r
  File "/.../site-packages/robin_stocks/__init__.py", line 1, in <module>
    from robin_stocks import gemini, robinhood, tda
  File "/.../site-packages/robin_stocks/tda/__init__.py", line 3, in <module>
    from .authentication import (generate_encryption_passcode, login,
  File "/.../site-packages/robin_stocks/tda/authentication.py", line 5, in <module>
    from cryptography.fernet import Fernet
  File "/.../site-packages/cryptography/fernet.py", line 14, in <module>
    from cryptography.hazmat.primitives import hashes, padding
  File "/.../site-packages/cryptography/hazmat/primitives/padding.py", line 11, in <module>
    from cryptography.hazmat.bindings._rust import (
pyo3_runtime.PanicException: Python API call failed
```

**Comment by W-M-D** [comment]
that's something to do with your python setup not the libs

**Comment by W-M-D** [comment]
https://cryptography.io/en/latest/installation/

**Comment by willswinson** [comment]
You are correct. Was cffi.

`pip3 uninstall cffi`

Followed by

`LDFLAGS=-L$(brew --prefix libffi)/lib CFLAGS=-I$(brew --prefix libffi)/include pip3 install cffi --no-binary :all:`

Fixed it.
