### ISSUE TITLE
Won't login

### ISSUE THREAD

**Issue by mxjake720** [jmfernandes/robin_stocks#417]
Traceback (most recent call last):
  File "C:\Users\jeffb\OneDrive\Documents\Crypto Bot\Robinhood - BTC-USD V2.py", line 13, in <module>
    rh.authentication.login(username, password, mfa_code=mfa_code)
  File "C:\Users\jeffb\AppData\Local\Programs\Python\Python311\Lib\site-packages\robin_stocks\robinhood\authentication.py", line 192, in login
    raise Exception('Error: Trouble connecting to robinhood API. Check internet connection.')
Exception: Error: Trouble connecting to robinhood API. Check internet connection.

**Comment by mxjake720** [comment]
Any suggestions?

**Comment by Adelantado** [comment]
#410 and #408 are related. Hope it helps.
