### ISSUE TITLE
rbh.authentication.login (username="....", password="....", mfa_code=totp) started failing on Dec 17

### ISSUE THREAD

**Issue by emmanuelsalawu** [jmfernandes/robin_stocks#521]
Robinhood Authentication through MFA as described here https://robin-stocks.readthedocs.io/en/latest/quickstart.html#with-mfa-entered-programmatically-from-time-based-one-time-password-totp was working until Dec 17. I have tried multiple times but unsuccessful. Is anyone experiencing a similar issue?

The error message is not very helpful.

```
Traceback (most recent call last):
  File "rhs.py", line 962, in f2
    rbh_ = rbh.authentication.login (username="....", password="....", mfa_code=totp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mycomputer/anaconda3/lib/python3.12/site-packages/robin_stocks/robinhood/authentication.py", line 198, in login
    raise Exception(data['detail'])
                    ~~~~^^^^^^^^^^
KeyError: 'detail'
```

I tried to print what `data` contains and obtained the following. (Note:  `data = request_post(url, payload)` within the `robin_stocks/robinhood/authentication.py`).

```{'verification_workflow': {'id': '***5d74a-****-****-9721-cb00a6d69***', 'workflow_status': 'workflow_status_internal_pending'}}```

Could it be that the `'client_id': 'c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS',` used in the `payload` used for authentication (within the `robin_stocks/robinhood/authentication.py` file) is no longer allowed by robinhood?

```
    url = login_url()
    payload = {
        'client_id': 'c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS',                                                                                                                                                             
        'expires_in': expiresIn,
        'grant_type': 'password',
        'password': password,
        'scope': scope,
        'username': username,
        'challenge_type': challenge_type,
        'device_token': device_token
    }
```

Any help will be greatly appreciated. Thank you.

**Comment by mitch-zink** [comment]
This was fixed recently, you need to pull the repo manually instead of using the package. The package was not updated 

‘’’
echo "🍺 Adding or updating Robin-Stocks as a submodule..."
if [ -d "robin_stocks" ]; then
    echo "🍺 Robin-Stocks submodule already exists. Pulling latest changes..."
    git -C robin_stocks pull origin master
else
    echo "🍺 Cloning Robin-Stocks as a submodule..."
    git submodule add https://github.com/jmfernandes/robin_stocks.git robin_stocks
    git submodule update --init --recursive
fi

echo "🍺 Installing Robin-Stocks in editable mode..."
pip install -e robin_stocks
‘’’

**Comment by SashaCroatia** [comment]
> This was fixed recently, you need to pull the repo manually instead of using the package. The package was not updated

Did just that. This is how I login:
`
#Login
load_dotenv()
rs.login(
    username=os.environ['robin_username'],
    password=os.environ['robin_password'],
    expiresIn=86400,
    by_sms=True,
    store_session=True
)
`
 but now I get a different error:
`
Traceback (most recent call last):
  File "C:\Users\...", line #, in <module>
    rs.login(
  File "C:\Users\[user]\anaconda3\lib\site-packages\robin_stocks\robinhood\authentication.py", line 190, in login
    _validate_sherrif_id(device_token=device_token, workflow_id=workflow_id, mfa_code=mfa_code)
  File "C:\Users\[user]\anaconda3\lib\site-packages\robin_stocks\robinhood\authentication.py", line 230, in _validate_sherrif_id
    if challenge_response["status"] == "validated":
KeyError: 'status'
`

??

**Comment by mitch-zink** [comment]
I use TOTP, here's my code if you want to try:

```
import pyotp
import robin_stocks.robinhood as r
from prefect.blocks.system import Secret
from prefect.logging import get_run_logger

def load_prefect_credentials():
    """
    Loads credentials from Prefect Secret blocks.
    """
    logger = get_run_logger()
    try:
        username = Secret.load("robinhood-username").get()
        password = Secret.load("robinhood-password").get()
        mfa_key = Secret.load("robinhood-mfa-key").get()
    except Exception as e:
        logger.error("💩 Missing Robinhood credentials or MFA key in Prefect Secrets.")
        raise ValueError("💩 Missing Robinhood credentials or MFA key in Prefect Secrets") from e

    if not all([username, password, mfa_key]):
        logger.error("💩 Robinhood credentials or MFA key are missing. Check Prefect Secrets.")
        raise ValueError("💩 Robinhood credentials or MFA key are missing. Check Prefect Secrets.")

    return username, password, mfa_key


def generate_totp(mfa_key):
    """
    Generates a TOTP code using the provided MFA key.
    """
    logger = get_run_logger()
    totp = pyotp.TOTP(mfa_key).now()
    logger.info("🍺 Generated TOTP (MFA PIN)")
    return totp


def login_robinhood():
    """
    Logs into Robinhood using Prefect Secret credentials and a required MFA TOTP.
    """
    logger = get_run_logger()
    username, password, mfa_key = load_prefect_credentials()
    totp = generate_totp(mfa_key)

    try:
        logger.info("🍺 Attempting to log in to Robinhood...")
        login_response = r.login(
            username=username,
            password=password,
            store_session=False,
            mfa_code=totp
        )

        if isinstance(login_response, dict) and "access_token" in login_response:
            logger.info("🍺 Successfully logged into Robinhood")
        else:
            detail = login_response.get("detail", "No details provided.")
            logger.error(f"❌ Login failed: {detail}")
            raise ValueError(f"❌ Login failed: {detail}")
    except Exception as e:
        logger.error(f"❌ Exception during login: {e}")
        raise
```

**Comment by emmanuelsalawu** [comment]
Thank you so much, @mitch-zink! Your proposed solution works for me too, and I am using TOTP. 
I will keep this open until after the market hours tomorrow to see if it continues to work.

**Comment by mitch-zink** [comment]
> Thank you so much, @mitch-zink! Your proposed solution works for me too, and I am using TOTP. I will keep this open until after the market hours tomorrow to see if it continues to work.

You're welcome, glad it's working for you

**Comment by mitch-zink** [comment]
> @mitch-zink from where we can get the mfa_key please ? its from the 2FA setting in robinhood website ? ![image](https://private-user-images.githubusercontent.com/28535890/397777044-a621affc-7aa9-4359-85fa-e228457af3fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MDcwMTQsIm5iZiI6MTczNDcwNjcxNCwicGF0aCI6Ii8yODUzNTg5MC8zOTc3NzcwNDQtYTYyMWFmZmMtN2FhOS00MzU5LTg1ZmEtZTIyODQ1N2FmM2ZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDE0NTgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZmRiYzg1NzRhNTQwODQ0ZWMzMzNmMTA3MTQzNjEzNTdhNTcwNjllZGE4MWVhOGNhNjFjOWEwZjE2Mzc1YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hb33v_wsS81SnGJth7okZAmqv13STl-jK5xC2ajgPIc)

Click Two-Factor Authentication, Authenticator app, then follow the steps to use the MFA key you get to generate the TOTP/MFA pin like I did above

**Comment by helhadry** [comment]
@mitch-zink thank you will try this.

**Comment by emmanuelsalawu** [comment]
Hello @helhadry ,

Try logging in using the MFA as described here https://robin-stocks.readthedocs.io/en/latest/quickstart.html#with-mfa-entered-programmatically-from-time-based-one-time-password-totp

```
import pyotp
import robin_stocks.robinhood as r
totp  = pyotp.TOTP("My2factorAppHere").now()
login = r.login('joshsmith@email.com','password', mfa_code=totp)
```

**Comment by helhadry** [comment]
@mitch-zink  @emmanuelsalawu  thank you for your help.

I tried to add the 2FA and selected the authentication app (Google authentication) but I can see only the backup code, where I can get the secret key (My2factorAppHere) ?

**Comment by emmanuelsalawu** [comment]
You can get it from the Robinson App or on the website. Kindly re-read the
instructions in the link I shared earlier. Go to Securityand Privacy —> Two
Factor Authentication. I can record a short screencast to share with you
when I get to my computerin case you still cannot find it.

**Comment by helhadry** [comment]
Yes I already did that but now I have only the 6 digits generated by Google authenticator app and If I put this code in the robin login it works fine, but I want to have something automatic to create that code without any human interaction.
the code that you suggest t to uses the "My2factorAppHere" and after that uses pyotp library to generate the otp code to use but I don't see where I can find that "My2factorAppHere".

thank you so much @emmanuelsalawu for your help on this.

**Comment by mcclouda2** [comment]
I have also tried what feels like every combo of logging in. I was able to login up through Jan 23 using this code snippet below. I switched over to MFA authentication using pyotp about a month ago, and I had a similar script working prior to that change using just user and password (with SMS code on login).
......
......
......
totp = pyotp.TOTP(mfa_key).now()
rs.authentication.login(username=robinhood_username,
password=robinhood_password,
expiresIn=secsExpired,
mfa_code=totp)

but get the following error.

Traceback (most recent call last):
File "", line 5, in
File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/robin_stocks/robinhood/authentication.py", line 190, in login
_validate_sherrif_id(device_token=device_token, workflow_id=workflow_id, mfa_code=mfa_code)
~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/robin_stocks/robinhood/authentication.py", line 233, in _validate_sherrif_id
if inquiries_response["type_context"]["result"] == "workflow_status_approved":
^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'status'

If I have my app open on my phone at the same time attempting to login it will ask for authentication there as well. But fails in python no matter which order I do things it feels.

Also - fairlly confident I have followed instructions here https://robin-stocks.readthedocs.io/en/latest/quickstart.html#with-mfa-entered-programmatically-from-time-based-one-time-password-totp exactly.

Thoughts? Thank you!

**Comment by mcclouda2** [comment]
@emmanuelsalawu, thank you. Makes sense and I should have tried that. Thats what I had working prior to December. This will work.

**Comment by No-Reality-Shows** [comment]
@emmanuelsalawu - Thanks for the information. Any guidance on using 2FA with SMS programmatically would be super helpful, because I'm not sure how this would work in an automated fashion (maybe a twilio phone number or something).

This change is a little frustrating and I'm curious about the reasoning. I know they recently launched "Robinhood Legend" app and a crypto API. I suspect they're trying to have more control over the automated trading on their platform.

**Comment by TrevorC18** [comment]
> Hello [@mcclouda2](https://github.com/mcclouda2) ,
> 
> The MFA authentication using pyotp has stopped working all together. A conversation with robin***d showed that they have now disallowed using TOTP from custom Authentication Apps (such as pyotp).
> 
> _Solution_ You could change your 2FA method to SMS and manually (or programmatically, which is more difficult) enter the code sent to your phone into the standard input when prompted.

Did you reach out to them or is this coversation in the public domain? Was there any indication of whether this is a permanent change or not?

**Comment by Dylan-86** [comment]
> Hello [@mcclouda2](https://github.com/mcclouda2) ,
> 
> The MFA authentication using pyotp has stopped working all together. A conversation with robin***d showed that they have now disallowed using TOTP from custom Authentication Apps (such as pyotp).
> 
> _Solution_ You could change your 2FA method to SMS and manually (or programmatically, which is more difficult) enter the code sent to your phone into the standard input when prompted.

How can they know where the authentication code come from? The code generated by pyotp is the same generated by Authy or Google Authenticator. Unless they see that the origin of the request does not come from the robinhood app/website, and block it for this reason.
No idea, for me the SMS thing is not viable for my scope, nor the in-app authentication. 
Right now I'm not using robin-stocks for active trading but more for position management (close at target or at stop, whichever gets hit - which would be possible from the app if only RH released a OCO kind of order). But if the authorization expires after a few hours/days, I want to make sure to re-authenticate automatically, not via SMS...

**Comment by sma202** [comment]
This is still an issue.

The Robinhood app on your phone will prompt you with a "is this you security check", upon an attempt to login on a separate pc.

Even if you accept on your phone, the script will fail, so it appears this extra security check on the phone is causing problems and I'm surprised that not a lot of people have raised this.

There's no way to disable Face ID, or change to SMS auth in the app, 2FA is also enabled and cannot be disabled. 

Short of contacting support and changing the auth, what's the short-term solution?

**Comment by slagonsky** [comment]
Hi, there!
For sma202
Reverting to 2FA with SMS does no good. I have 2FA over SMS and never changed it to either FaceID or authentication app. This morning a try to log in using MFA code just pops up a confirmation on the phone app. No SMS been sent with code. Of course, confirming on the phone fails script anyway with error {'detail': 'Authentication credentials were not provided.'} in module authentication.py
My guess RH login procedure must be rewritten by robin-stocks author.

**Comment by slagonsky** [comment]
@sma202 
I've got it figured out. Thanks to https://github.com/Dylan-86
https://github.com/jmfernandes/robin_stocks/issues/537#issuecomment-2653137652
His code replaces original authentication.py (C:\Program Files\Python313\Lib\site-packages\robin_stocks\robinhood\)
I was able to log in to RH with app confirmation. It created a new .pickle file.
After that I reverted to original authentication.py and it used .pickle as before. I guess it will work until this new .pickle is expired.
