### ISSUE TITLE
Unable to login anymore - firstly got reported as pickle is invalid

### ISSUE THREAD

**Issue by nat2k5us** [jmfernandes/robin_stocks#524]
Unable to login anymore - firstly got reported as pickle is invalid
Then after many attempts still not able to get past the key error when using the simple login method
`import os
import requests
import pyotp

# Replace the endpoint with the correct one if necessary
url = "https://api.robinhood.com/oauth2/token/"
totp  = pyotp.TOTP("My2factorAppHere").now()
print(f"    TOTP: {totp}")
payload = {
    "username": os.getenv("RH_USERNAME"),
    "password": os.getenv("RH_PASSWORD"),
    "mfa_code": totp,
    "grant_type": "password",
    "scope": "internal",
    "client_id": "c82SH0WZNTt8bRhZR4B0RQvmfxo3x10c",
}

response = requests.post(url, data=payload)
print(response.json())  # Inspect the API response

Gives the error
    TOTP: xxxxxxx
{'error': 'invalid_client'}
`
Second way:

`def login_to_robinhood():
    username = os.getenv("RH_USERNAME")
    password = os.getenv("RH_PASSWORD")
    if not username or not password:
        print("Error: RH_USERNAME or RH_PASSWORD environment variables are not set.")
        return
    logged_in = r.login(username, password)
    print(f"Login: {logged_in}")
    return logged_in`

got these error 
  File "/Users/nbontha/dev/rh/myprofits/libs/robin_stocks/robin_stocks/robinhood/authentication.py", line 190, in login
    raise Exception(data['detail'])
Exception: Unable to log in with provided credentials.

**Comment by nat2k5us** [comment]
I used the authenticator App and the latest robin_stock code and that looks to have solved the issue

```python
import os
import pyotp
import argparse
import robin_stocks.robinhood as r


def generate_token():
    totp = pyotp.TOTP("My2factorAppHere").now()
    print(f"TOTP: {totp}")

def login(mfa_code):
    username = os.getenv("RH_USERNAME")
    password = os.getenv("RH_PASSWORD")
    if not username or not password:
        print("Error: RH_USERNAME or RH_PASSWORD environment variables are not set.")
        exit(1)
    # Add your login logic here
    print(f"User parameter: {mfa_code}")
    login = r.login(username, password, mfa_code=mfa_code)
    print(f"Login: {login}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Process command line arguments.")
    parser.add_argument("action", choices=["token", "login"], help="Action to perform: 'token' or 'login'")
    parser.add_argument("mfa_code", nargs='?', help="User parameter for login action")
    args = parser.parse_args()

    if args.action == "token":
        generate_token()
    elif args.action == "login":
        if args.mfa_code:
            login(args.mfa_code)
        else:
            print("Error: user_param is required for login action.")
            exit(1)
```

**Comment by Two20Two21** [comment]
Latest robin-stocks code?  I used the code below with the latest release plus the authentication.py module from two weeks ago with the sheriff module and it no longer works for me.  It doesn't prompt me for the MFA code, it just errors out.


import robin_stocks.robinhood
import pyotp
from datetime import *

now = datetime.now()
totp = pyotp.TOTP("KACUJH6EKZZCVZ6K").now()
print("TOTP: " + str(totp))
login = robin_stocks.robinhood.login(my_user_name, my_password, store_session=True)

**Comment by nat2k5us** [comment]
have you setup an authenticator app?
then you get the 6 digit code from there 

In your login enter the MFA code 

```python
    login = r.login(username, password, mfa_code=mfa_code_from_authenticator_of_robinhood)
```

**Comment by regholl2023** [comment]
I guess I'm just dumb because i have been trying for two days wit this script and no success,import os
import pyotp
import argparse
import robin_stocks.robinhood as r


def generate_token():
    totp = pyotp.TOTP("My2factorAppHere").now()
    print(f"TOTP: {totp}")

def login(mfa_code):
    username = os.getenv("RH_USERNAME")
    password = os.getenv("RH_PASSWORD")
    if not username or not password:
        print("Error: RH_USERNAME or RH_PASSWORD environment variables are not set.")
        exit(1)
    # Add your login logic here
    print(f"User parameter: {mfa_code}")
    login = r.login(username, password, mfa_code=mfa_code)
    print(f"Login: {login}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Process command line arguments.")
    parser.add_argument("action", choices=["token", "login"], help="Action to perform: 'token' or 'login'")
    parser.add_argument("mfa_code", nargs='?', help="User parameter for login action")
    args = parser.parse_args()

    if args.action == "token":
        generate_token()
    elif args.action == "login":
        if args.mfa_code:
            login(args.mfa_code)
        else:
            print("Error: user_param is required for login action.")
            exit(1)

**Comment by Two20Two21** [comment]
@nat2k5us , thanks for responding.  yes, I am passing the mfa code (see my updated code above).  If you look at the attachment, that is where everything goes wrong in authentication.py.  Right below the blue line in the attached file is: if 'mfa_required' in data:
The code is expecting 'mfa_required' in data but nothing is in data except verification_workflow (also shown in the attachment).  As a result, it doesn't prompt for the MFA code.

This broke for me two weeks ago.  I loaded the new authentication.py file with the sheriff module and that fixed it.  Now it's broken again.


![Login Error](https://github.com/user-attachments/assets/4d916141-8ad9-4141-8ded-039c250334a5)

**Comment by nat2k5us** [comment]
Can you try it on this repo - I will try and backup my pickle file and try again to login as well

also, the the msft authenticator app is what I am using - I remove the old Robinhood and re-added it again with a new code
[https://github.com/nat2k5us/rh_login](url)

**Comment by nat2k5us** [comment]
It worked (in the repo I shared) after I deleted the .pickle.robinhood and tried the login again

```python
 - Firstly ensure your correct username and password are present in the env
 - make sure you give enough time for the mfa_code
./run-login-test.sh login mfa_code_from_authenticator_app
```

**Comment by Dadudekc** [comment]
> Unable to login anymore - firstly got reported as pickle is invalid Then after many attempts still not able to get past the key error when using the simple login method
> 
> I have 2FA enabled with the authenticator app - so when the login/pikle has expired I would get prompted to enter the authenticator app code in the console - but now that is no longer is happening
> 
> The client id is being reported as invalid - is there a new client id - how to get a valid id?
> 
> Thank you
> 
> ```python
> import os
> import requests
> import pyotp
> 
> 
> ### Replace the endpoint with the correct one if necessary
> url = "https://api.robinhood.com/oauth2/token/"
> totp  = pyotp.TOTP("My2factorAppHere").now()
> print(f"    TOTP: {totp}")
> payload = {
>     "username": os.getenv("RH_USERNAME"),
>     "password": os.getenv("RH_PASSWORD"),
>     "mfa_code": totp,
>     "grant_type": "password",
>     "scope": "internal",
>     "client_id": "c82SH0WZNTt8bRhZR4B0RQvmfxo3x10c",
> }
> 
> response = requests.post(url, data=payload)
> print(response.json())  # Inspect the API response
> 
> Gives the error
>     TOTP: xxxxxxx
> {'error': 'invalid_client'}
> 
> Second way:
> 
> 
> def login_to_robinhood():
>     username = os.getenv("RH_USERNAME")
>     password = os.getenv("RH_PASSWORD")
>     if not username or not password:
>         print("Error: RH_USERNAME or RH_PASSWORD environment variables are not set.")
>         return
>     logged_in = r.login(username, password)
>     print(f"Login: {logged_in}")
>     return logged_in
> ```
> 
> got these error File "/Users/xxxxxx/dev/rh/myprofits/libs/robin_stocks/robin_stocks/robinhood/authentication.py", line 190, in login raise Exception(data['detail']) Exception: Unable to log in with provided credentials.

import requests
import uuid
import getpass

BASE_URL = "https://api.robinhood.com/oauth2/token/"

def login_robinhood():
    """
    Logs into Robinhood with captured client_id and additional debugging.
    """
    username = input("Enter Robinhood username: ")
    password = getpass.getpass("Enter Robinhood password: ")
    device_token = str(uuid.uuid4())  # Generate a unique device token

    payload = {
        "username": username,
        "password": password,
        "grant_type": "password",
        "scope": "internal",
        "client_id": "c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS",  # Replace with extracted client_id
        "device_token": device_token,
        "challenge_type": "sms",
    }

    headers = {
        "accept": "*/*",
        "accept-encoding": "gzip, deflate, br, zstd",
        "accept-language": "en-US,en;q=0.9",
        "content-type": "application/json",
        "origin": "https://robinhood.com",
        "referer": "https://robinhood.com/",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0",
        "x-robinhood-api-version": "1.431.4",
    }

    try:
        print("Attempting login...")
        response = requests.post(BASE_URL, json=payload, headers=headers)
        response.raise_for_status()  # Raise HTTPError for bad responses

        data = response.json()
        print("Login response (raw):", data)

        if "mfa_required" in data and data["mfa_required"]:
            print("MFA required. A code has been sent to your phone.")
            mfa_code = input("Enter the MFA (SMS) code you received: ")

            # Retry login with the MFA code
            payload["mfa_code"] = mfa_code
            response = requests.post(BASE_URL, json=payload, headers=headers)
            response.raise_for_status()
            data = response.json()
            print("MFA login response (raw):", data)

        if "access_token" in data:
            print("Login successful!")
            return data
        else:
            print("Login failed. Response:", data)
            return None

    except requests.exceptions.HTTPError as http_err:
        print(f"HTTP error: {http_err}")
        print("Response text:", response.text)
    except Exception as e:
        print(f"An error occurred: {e}")
    return None

if __name__ == "__main__":
    token = login_robinhood()
    if token:
        print("Access Token:", token["access_token"])
    else:
        print("Login failed.")

**Comment by Dadudekc** [comment]
1. **Invalid Client ID**  
   The client ID you're using seems outdated. Robinhood occasionally rotates client IDs. The one that’s been working recently is:  
   `"c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS"`

2. **MFA with Authenticator App**  
   If you're using an authenticator app for 2FA, you'll need to explicitly handle the TOTP code during login. This ensures your `mfa_code` gets sent correctly.

3. **Environment Variables for Credentials**  
   To keep things secure, make sure your `RH_USERNAME`, `RH_PASSWORD`, and `RH_2FA_SECRET` (TOTP secret) are stored as environment variables.

Here’s a code snippet that fixes the issues and works with MFA + the updated client ID:

```python
import os
import requests
import pyotp

def login_robinhood():
    """
    Logs into Robinhood using TOTP-based 2FA.
    Make sure RH_USERNAME, RH_PASSWORD, and RH_2FA_SECRET are set as environment variables.
    """
    # Get credentials from environment variables
    username = os.getenv("RH_USERNAME")
    password = os.getenv("RH_PASSWORD")
    totp_secret = os.getenv("RH_2FA_SECRET")  # Your authenticator app's secret

    if not username or not password or not totp_secret:
        print("Error: Missing RH_USERNAME, RH_PASSWORD, or RH_2FA_SECRET environment variable.")
        return None

    # Generate the TOTP code
    totp = pyotp.TOTP(totp_secret).now()
    print(f"Generated TOTP: {totp}")

    # API endpoint and payload
    url = "https://api.robinhood.com/oauth2/token/"
    payload = {
        "username": username,
        "password": password,
        "mfa_code": totp,
        "grant_type": "password",
        "scope": "internal",
        "client_id": "c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS",  # Latest client ID
    }

    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    }

    try:
        response = requests.post(url, data=payload, headers=headers)
        response.raise_for_status()
        data = response.json()

        if "access_token" in data:
            print("Login successful!")
            return data
        else:
            print("Login failed. Response:", data)
            return None

    except requests.exceptions.HTTPError as http_err:
        print(f"HTTP error: {http_err}")
        if response.text:
            print("Response text:", response.text)
    except Exception as e:
        print(f"An error occurred: {e}")

    return None

if __name__ == "__main__":
    token = login_robinhood()
    if token:
        print("Access Token:", token["access_token"])
    else:
        print("Failed to log in to Robinhood.")
```

### Why This Works:
- It uses the **latest client ID** known to work.
- Handles **TOTP generation** for MFA using `pyotp` (make sure your secret is correct).
- Stores credentials securely using **environment variables**.
- Includes error handling for API responses.

**Next Steps**:
1. Double-check your environment variables (`RH_USERNAME`, `RH_PASSWORD`, `RH_2FA_SECRET`) are set and correct.
2. Ensure your TOTP secret is synced with your authenticator app.
3. Run the script and check for any specific errors in the output.

**Comment by regholl2023** [comment]
i got this error back,Traceback (most recent call last):
  File "e:\robin_stocks\examples\robinhood examples\two_factor_log_in.py", line 27, in <module>
    login = r.login(os.environ['RH_USERNAME'],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\robin_stocks\venv\Lib\site-packages\robin_stocks\robinhood\authentication.py", line 190, in login
    _validate_sherrif_id(device_token=device_token, workflow_id=workflow_id, mfa_code=mfa_code)
  File "E:\robin_stocks\venv\Lib\site-packages\robin_stocks\robinhood\authentication.py", line 230, in _validate_sherrif_id
    if challenge_response["status"] == "validated":
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'status'

**Comment by regholl2023** [comment]
now i'm getting back this error, HTTP error: 400 Client Error: Bad Request for url: https://api.robinhood.com/oauth2/token/
Response text: {"detail":"This version of Robinhood is no longer supported. Please update your app or use Robinhood for Web to log in to your account."}
Failed to log in to Robinhood.

**Comment by nciocchini3** [comment]
> @nat2k5us , thanks for responding. Yes, I am passing the mfa code (see my updated code above). If you look at the attachment, that is where everything goes wrong in authentication.py. Right below the blue line in the attached file is: if 'mfa_required' in data: The code is expecting 'mfa_required' in data but nothing is in data except verification_workflow (also shown in the attachment). As a result, it doesn't prompt for the MFA code. I tried changing that if statement to if True so I could input the MFA code. It tells me wrong MFA code, probably because it is not expecting one.
> 
> This broke for me two weeks ago. I loaded the new authentication.py file with the sheriff module and that fixed it. Now it's broken again.
> 
> ![Login Error](https://private-user-images.githubusercontent.com/190970725/397998023-4d916141-8ad9-4141-8ded-039c250334a5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5NDgzNTAsIm5iZiI6MTczNTk0ODA1MCwicGF0aCI6Ii8xOTA5NzA3MjUvMzk3OTk4MDIzLTRkOTE2MTQxLThhZDktNDE0MS04ZGVkLTAzOWMyNTAzMzRhNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwM1QyMzQ3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjdhMmIxOWI4OWZjZDJhOTYyYTk1NTIwZmFlY2EyNmExNjUzNDk5YmE3NDA0Yjc1MDliOTYwY2FiZTdkNjA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-LrnyM9CoMeiFXZf2es1fqYjz7eDDw10GpphL_Fdi2k)

Any success with this? I am experiencing the same problem, I am providing the correct MFA code and updated to latest verison of the repo, still fall into the state 'workflow_status_internal_pending' inside _validate_sherrif_id method ...

**Comment by finlop** [comment]
anyone know how to make the code work for device approvals. i only get device approvals now from my iphone robinhood app. and then the code i run waits for the device approval to be approved and then checks to see if i can log in successfully. but it never sees that i approved the device.

import random
import getpass
import os
import pickle
import requests
import time

Generate a unique device token
def generate_device_token():
"""Generates a unique device token."""
rands = []
for _ in range(16):
rand = random.randint(0, 255)
rands.append(rand)

hexa = [str(hex(i + 256)).lstrip("0x")[1:] for i in range(256)]
token = ""
for i, r in enumerate(rands):
    token += hexa[r]
    if i in [3, 5, 7, 9]:
        token += "-"
return token
Respond to challenges
def respond_to_challenge(challenge_id, sms_code):
"""Responds to a challenge with the provided code."""
url = f"[https://api.robinhood.com/challenge/{challenge_id}/respond/](https://api.robinhood.com/challenge/%7Bchallenge_id%7D/respond/)"
payload = {"response": sms_code}
response = requests.post(url, json=payload)
return response.json()

Save and load session data
def save_session(data, pickle_name="robinhood_session.pickle"):
"""Saves session data to a pickle file."""
with open(pickle_name, "wb") as f:
pickle.dump(data, f)

def load_session(pickle_name="robinhood_session.pickle"):
"""Loads session data from a pickle file if it exists."""
if os.path.exists(pickle_name):
with open(pickle_name, "rb") as f:
return pickle.load(f)
return None

def handle_verification_workflow(device_token, workflow_id):
"""Handles verification workflow for device approval."""
print("Handling verification workflow. Please approve the login request on your device.")
url = f"https://api.robinhood.com/pathfinder/user_machine/"
payload = {
"device_id": device_token,
"flow": "suv",
"input": {"workflow_id": workflow_id}
}
response = requests.post(url, json=payload)
if response.status_code == 200:
print("Verification workflow initiated successfully. Waiting for approval...")
else:
raise Exception(f"Failed to initiate verification workflow: {response.text}")

inquiries_url = f"https://api.robinhood.com/pathfinder/inquiries/{response.json()['id']}/user_view/"
max_attempts = 5  # Increase retries to 30 attempts (5 minutes total)
delay_between_attempts = 10  # 10 seconds between checks

for attempt in range(max_attempts):
    print(f"Attempt {attempt + 1}: Checking approval status...")
    try:
        inquiry_response = requests.get(inquiries_url, timeout=10).json()
        status = inquiry_response["type_context"]["context"]["sheriff_challenge"]["status"]
        print(f"Device approval status: {status}")

        if status == "approved":
            print("Device approval successful!")
            return

        if status == "denied":
            raise Exception("Device approval was denied.")

    except Exception as e:
        print(f"Error while checking approval status: {e}")

    time.sleep(delay_between_attempts)

print("Device approval timed out. Please ensure you approved the login request.")


# Login to Robinhood
def robinhood_login(username=None, password=None, expires_in=86400, scope="internal"):
"""Logs into Robinhood and handles verification workflows."""
device_token = generate_device_token()
print("Generated Device Token:", device_token)

url = "https://api.robinhood.com/oauth2/token/"
payload = {
    "grant_type": "password",
    "scope": scope,
    "client_id": "c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS",
    "device_token": device_token,
    "username": username,
    "password": password,
}

session = load_session()
if session:
    print("Using saved session.")
    return session["access_token"]

response = requests.post(url, data=payload)
data = response.json()

if response.status_code == 200:
    print("Login successful.")
    save_session(data)
    return data["access_token"]

if "verification_workflow" in data:
    workflow_id = data["verification_workflow"]["id"]
    print(f"Verification workflow triggered. Workflow ID: {workflow_id}")
    handle_verification_workflow(device_token, workflow_id)
    response = requests.post(url, data=payload)
    data = response.json()
    if response.status_code == 200:
        print("Login successful after verification workflow.")
        save_session(data)
        return data["access_token"]

print("Failed to log in:", data)
return None
Main flow
if name == "main":
username = input("Enter your Robinhood username: ")
password = getpass.getpass("Enter your Robinhood password: ")
token = robinhood_login(username=username, password=password)
if token:
print("Access token:", token)
else:
print("Failed to log in.")

Verification workflow triggered. Workflow ID: 00e60f42-de4c-4282-ad7d-e9c01a0206e1
Handling verification workflow. Please approve the login request on your device.
Verification workflow initiated successfully. Waiting for approval...
Attempt 1: Checking approval status...
Device approval status: issued
Attempt 2: Checking approval status...
Device approval status: issued
Attempt 3: Checking approval status...
Device approval status: issued
Attempt 4: Checking approval status...
Device approval status: issued
Attempt 5: Checking approval status...
Device approval status: issued
Device approval timed out. Please ensure you approved the login request.
Failed to log in: {'verification_workflow': {'id': '00e60f42-de4c-4282-ad7d-e9c01a0206e1', 'workflow_status': 'workflow_status_internal_pending'}}
Failed to log in.

**Comment by jogepa** [comment]
@finlop I'm getting the same error... Still can't figure out how to get my code to work with device approvals.
